// Auto-generated by scripts/extract-gallery.mjs
// Run: npm run extract-gallery

import type { MapPhoto } from '@/lib/photoMapData'

export const galleryData: MapPhoto[] = [
  {
    id: 'personal',
    lat: 10.7782,
    lng: 106.7013,
    src: '/images/gallery/personal.jpeg',
    timestamp: '2026-02-01',
    comment: 'test',
    location: 'Thủ Đức, Thành phố Hồ Chí Minh, Việt Nam',
  },
]
