// Auto-generated by scripts/extract-gallery.mjs
// Run: npm run extract-gallery

import type { MapPhoto } from '@/lib/photoMapData'

export const staticGalleryData: MapPhoto[] = [
  {
    id: '20241227-095237',
    lat: null,
    lng: null,
    src: '/images/static_gallery/20241227_095237.jpg',
    timestamp: '2024-12-27',
    comment: '',
    location: '',
  },
  {
    id: 'img-2336',
    lat: null,
    lng: null,
    src: '/images/static_gallery/IMG_2336.JPG',
    timestamp: '2022-08-20',
    comment: '',
    location: '',
  },
  {
    id: 'img-2529',
    lat: null,
    lng: null,
    src: '/images/static_gallery/IMG_2529.JPG',
    timestamp: '2022-08-27',
    comment: 'test',
    location: '',
  },
]
