// Auto-generated by scripts/extract-gallery.mjs
// Run: npm run extract-gallery

import type { MapPhoto } from '@/lib/photoMapData'

export const staticGalleryData: MapPhoto[] = [
  {
    id: '20241227-095237',
    lat: 34.11801350443755,
    lng: -118.30040893104093,
    src: '/images/static_gallery/20241227_095237.jpg',
    timestamp: '2024-12-27',
    comment: '',
    location: 'Los Angeles, California, United States',
  },
  {
    id: 'img-2336',
    lat: 47.61043820985823,
    lng: -122.33535422875914,
    src: '/images/static_gallery/IMG_2336.JPG',
    timestamp: '2022-08-20',
    comment: '',
    location: 'Seattle, Washington, United States',
  },
  {
    id: 'img-2529',
    lat: 50.059597886335425,
    lng: -122.9590564635058,
    src: '/images/static_gallery/IMG_2529.JPG',
    timestamp: '2022-08-27',
    comment: 'test',
    location: 'Whistler Resort Municipality, British Columbia, Canada',
  },
]
