import { readdirSync, readFileSync, statSync, writeFileSync } from 'fs'
import { join, parse, extname } from 'path'
import exifr from 'exifr'

const DELAY_MS = 1100

function sleep(ms) {
  return new Promise(r => setTimeout(r, ms))
}

async function reverseGeocode(lat, lng) {
  const url = `https://nominatim.openstreetmap.org/reverse?lat=${lat}&lon=${lng}&format=json&zoom=10`
  const res = await fetch(url, {
    headers: { 'User-Agent': 'personal-portfolio/1.0' },
  })
  const data = await res.json()
  const a = data.address || {}
  const city = a.city || a.town || a.village || ''
  const country = a.country || ''

  let region = ''
  if (a.state && a.state !== city) {
    region = a.state
  } else if (a.county && a.county !== city) {
    region = a.county
  }

  if (!region && data.display_name) {
    const parts = data.display_name.split(', ').map(s => s.trim())
    const known = new Set([
      a.house_number, a.road, a.neighbourhood, a.suburb,
      a.city, a.town, a.village, a.hamlet,
      a.postcode, country, a.country_code,
    ].filter(Boolean))
    const extra = parts.filter(p => !known.has(p))
    region = extra[0] || ''
  }

  return [city, region, country].filter(Boolean).join(', ')
}

const IMAGE_EXTS = new Set(['.jpg', '.jpeg', '.png', '.heic', '.HEIC', '.JPG', '.JPEG', '.PNG'])
const GALLERY_DIR = 'public/images/gallery'
const STATIC_GALLERY_DIR = 'public/images/static_gallery'

function loadExistingEntries(filePath) {
  const map = {}
  try {
    const content = readFileSync(filePath, 'utf-8')
    const blockRegex = /  \{\n[\s\S]*?  \},/g
    const idRegex = /id:\s+'([^']+)'/
    let match
    while ((match = blockRegex.exec(content)) !== null) {
      const block = match[0]
      const idMatch = idRegex.exec(block)
      if (idMatch) {
        map[idMatch[1]] = block
      }
    }
  } catch {
    // File doesn't exist yet
  }
  return map
}

function writeDataFile(filePath, varName, entries) {
  const output = `// Auto-generated by scripts/extract-gallery.mjs
// Run: npm run extract-gallery

import type { MapPhoto } from '@/lib/photoMapData'

export const ${varName}: MapPhoto[] = [
${entries.join('\n')}
]
`

  console.log(output)
  writeFileSync(filePath, output, 'utf-8')
  console.log(`\nWritten to ${filePath} (${entries.length} photos)`)
}

async function processDirectory(dir, srcPrefix, outputFile, varName, existingMap, skipGeocode) {
  const files = readdirSync(dir)
    .filter(f => IMAGE_EXTS.has(extname(f)))
    .sort()

  if (files.length === 0) {
    console.log('No images found in', dir)
    writeDataFile(outputFile, varName, [])
    return
  }

  const entries = []

  for (const file of files) {
    const filePath = join(dir, file)
    const id = parse(file).name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')

    if (existingMap && existingMap[id]) {
      entries.push(existingMap[id])
      console.log(`  ${file} → preserved existing entry`)
      continue
    }

    const stats = statSync(filePath)

    let lat = null
    let lng = null

    let timestamp
    try {
      const exif = await exifr.parse(filePath, { gps: true })
      timestamp = exif?.DateTimeOriginal
        ? new Date(exif.DateTimeOriginal).toISOString().split('T')[0]
        : stats.birthtime.toISOString().split('T')[0]
      lat = exif?.latitude ?? null
      lng = exif?.longitude ?? null
      if (lat === null) console.log(`  ${file} → no GPS data`)
    } catch (e) {
      console.log(`  ${file} → error: ${e.message}`)
      timestamp = stats.birthtime.toISOString().split('T')[0]
    }

    const latStr = lat !== null ? lat.toFixed(4) : 'null'
    const lngStr = lng !== null ? lng.toFixed(4) : 'null'

    let location = ''

    if (!skipGeocode && lat !== null && lng !== null) {
      try {
        location = (await reverseGeocode(lat, lng)).replace(/'/g, "\\'")
        console.log(`  ${file} → ${location}`)
        await sleep(DELAY_MS)
      } catch {
        console.log(`  ${file} → geocode failed`)
      }
    }

    const entry = `  {
    id: '${id}',
    lat: ${latStr},
    lng: ${lngStr},
    src: '${srcPrefix}/${file}',
    timestamp: '${timestamp}',
    comment: '',
    location: '${location}',
  },`

    entries.push(entry)
  }

  writeDataFile(outputFile, varName, entries)
}

async function main() {
  // Process gallery/ (preserve existing entries)
  console.log('=== Gallery ===')
  const galleryExisting = loadExistingEntries('src/lib/galleryData.ts')
  await processDirectory(GALLERY_DIR, '/images/gallery', 'src/lib/galleryData.ts', 'galleryData', galleryExisting)

  // Process static_gallery/ (preserve existing entries)
  console.log('\n=== Static Gallery ===')
  const staticExisting = loadExistingEntries('src/lib/staticGalleryData.ts')
  await processDirectory(STATIC_GALLERY_DIR, '/images/static_gallery', 'src/lib/staticGalleryData.ts', 'staticGalleryData', staticExisting, true)
}

main().catch(console.error)
