import { readdirSync, statSync, writeFileSync } from 'fs'
import { join, parse, extname } from 'path'
import exifr from 'exifr'

const DELAY_MS = 1100

function sleep(ms) {
  return new Promise(r => setTimeout(r, ms))
}

async function reverseGeocode(lat, lng) {
  const url = `https://nominatim.openstreetmap.org/reverse?lat=${lat}&lon=${lng}&format=json&zoom=10`
  const res = await fetch(url, {
    headers: { 'User-Agent': 'personal-portfolio/1.0' },
  })
  const data = await res.json()
  const a = data.address || {}
  return a.city || a.town || a.village || a.county || a.state || ''
}

const GALLERY_DIR = 'public/images/gallery'
const IMAGE_EXTS = new Set(['.jpg', '.jpeg', '.png', '.heic', '.HEIC', '.JPG', '.JPEG', '.PNG'])

async function main() {
  const files = readdirSync(GALLERY_DIR)
    .filter(f => IMAGE_EXTS.has(extname(f)))
    .sort()

  if (files.length === 0) {
    console.log('No images found in', GALLERY_DIR)
    writeEmpty()
    return
  }

  const entries = []

  for (const file of files) {
    const filePath = join(GALLERY_DIR, file)
    const id = parse(file).name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')
    const stats = statSync(filePath)

    let lat = null
    let lng = null

    let timestamp
    try {
      const exif = await exifr.parse(filePath, { gps: true })
      timestamp = exif?.DateTimeOriginal
        ? new Date(exif.DateTimeOriginal).toISOString().split('T')[0]
        : stats.birthtime.toISOString().split('T')[0]
      lat = exif?.latitude ?? null
      lng = exif?.longitude ?? null
      if (lat === null) console.log(`  ${file} → no GPS data`)
    } catch (e) {
      console.log(`  ${file} → error: ${e.message}`)
      timestamp = stats.birthtime.toISOString().split('T')[0]
    }

    const latStr = lat !== null ? lat.toFixed(4) : 'null'
    const lngStr = lng !== null ? lng.toFixed(4) : 'null'

    let location = ''
    if (lat !== null && lng !== null) {
      try {
        location = (await reverseGeocode(lat, lng)).replace(/'/g, "\\'")
        console.log(`  ${file} → ${location}`)
        await sleep(DELAY_MS)
      } catch {
        console.log(`  ${file} → geocode failed`)
      }
    }

    const entry = `  {
    id: '${id}',
    lat: ${latStr},
    lng: ${lngStr},
    src: '/images/gallery/${file}',
    timestamp: '${timestamp}',
    comment: '',
    location: '${location}',
  },`

    entries.push(entry)
  }

  writeGallery(entries)
}

function writeGallery(entries) {
  const output = `// Auto-generated by scripts/extract-gallery.mjs
// Run: npm run extract-gallery

import type { MapPhoto } from '@/lib/photoMapData'

export const galleryData: MapPhoto[] = [
${entries.join('\n')}
]
`

  console.log(output)
  writeFileSync('src/lib/galleryData.ts', output, 'utf-8')
  console.log(`\nWritten to src/lib/galleryData.ts (${entries.length} photos)`)
}

function writeEmpty() { writeGallery([]) }

main().catch(console.error)
